global using FotoQuestApi.Configuration;
global using FotoQuestApi.Database;
global using FotoQuestApi.FileSystem;
global using FotoQuestApi.Model;
global using FotoQuestApi.Model.Exceptions;
global using FotoQuestApi.Web.Models;
global using FotoQuestApi.ImageProcess;
global using Serilog;
global using Serilog.Events;